import type { RawReportItem } from "@/lib/credit-classification";

export const sampleRaw: RawReportItem[] = [
  {
    id: "r1",
    name: "Capital One Bank",
    kind: "Account",
    subtype: "Revolving",
    balance: "$1,240",
    status: "Open",
    bureaus: ["EQ", "EX", "TU"],
    openDate: "03/2021",
  },
  {
    id: "r2",
    name: "Discover It",
    kind: "Account",
    subtype: "Revolving",
    balance: "$0",
    status: "Open",
    bureaus: ["EQ", "EX"],
    openDate: "07/2019",
  },
  {
    id: "r3",
    name: "Midland Funding LLC",
    kind: "Account",
    subtype: "Collection",
    balance: "$4,820",
    status: "Collection",
    bureaus: ["EQ", "EX", "TU"],
    dofd: "11/2024",
  },
  {
    id: "r4",
    name: "Portfolio Recovery Associates",
    kind: "Account",
    subtype: "Collection",
    balance: "$3,418",
    status: "Collection",
    bureaus: ["EQ", "TU"],
    dofd: "08/2023",
  },
  {
    id: "r5",
    name: "Chase Bank",
    kind: "Account",
    subtype: "Revolving",
    balance: "$2,150",
    status: "Charge-Off",
    bureaus: ["EQ", "EX", "TU"],
    dofd: "04/2025",
  },
  {
    id: "r6",
    name: "Navient",
    kind: "Account",
    subtype: "Student Loan",
    balance: "$18,400",
    status: "Late 90",
    bureaus: ["EQ", "EX", "TU"],
    dofd: "01/2025",
  },
  {
    id: "r7",
    name: "Bank of America",
    kind: "Inquiry",
    status: "Hard",
    bureaus: ["EQ"],
    linkedCreditor: "Bank of America",
  },
  {
    id: "r8",
    name: "Synchrony Bank",
    kind: "Inquiry",
    status: "Hard",
    bureaus: ["EX", "TU"],
  },
  {
    id: "r9",
    name: "Chapter 7 Bankruptcy",
    kind: "Public Record",
    balance: "—",
    status: "Discharged",
    bureaus: ["EQ", "EX", "TU"],
    dofd: "09/2022",
  },
  {
    id: "r10",
    name: "Wells Fargo Auto",
    kind: "Account",
    subtype: "Auto Loan",
    balance: "$12,800",
    status: "Open",
    bureaus: ["EQ", "EX", "TU"],
    openDate: "05/2023",
  },
  {
    id: "r11",
    name: "Self Lender",
    kind: "Account",
    subtype: "Secured Loan",
    balance: "$0",
    status: "Closed",
    bureaus: ["EQ", "TU"],
    openDate: "01/2022",
  },
  {
    id: "r12",
    name: "Credit One Bank",
    kind: "Account",
    subtype: "Revolving",
    balance: "$640",
    status: "Late 30",
    bureaus: ["EX"],
    dofd: "06/2026",
  },
];
