/**
 * Generates AUTHORIZATION_MAP.md from the live database.
 *
 * WHY THIS IS A GENERATOR AND NOT A DOCUMENT
 *
 * The hand-written map went stale in the worst possible way: it was verified
 * at migration 0021, the schema reached 0219, and every line was still
 * labelled **FACT**. A reader has no reason to doubt a fact. Five of its
 * load-bearing claims were false — that no teams or departments tables
 * existed, that `agency_memberships` carried no scope, that
 * `authorized_team` was free text.
 *
 * A document that must be remembered will be forgotten. This one is derived,
 * so `npm run db:authmap` after any migration reproduces it exactly, and a
 * diff shows what the migration actually changed about who may reach what.
 *
 * It states WHAT IS, never what should be. Doctrine lives in CLAUDE.md and
 * behaviour is asserted by `rls-matrix.mjs` against real users — this only
 * shows the surface both of those talk about.
 *
 *   node supabase/scripts/authorization-map.mjs            # write the file
 *   node supabase/scripts/authorization-map.mjs --stdout   # print instead
 *
 * Run from `creditverse-platform`.
 */
import { writeFileSync } from "node:fs";
import { createSyncQuery, readAccessToken, readProjectRef } from "./lib/sync-query.mjs";

const { query: q, close } = createSyncQuery({
  projectRef: readProjectRef(),
  token: readAccessToken(),
  baseUrl: import.meta.url,
});

/* ── One query per subject, not one per row (rule 14 applies to tools too) ── */

const tables = q(`
  select c.relname as table, c.relrowsecurity as rls, c.relforcerowsecurity as forced,
         obj_description(c.oid, 'pg_class') as note
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relkind in ('r','p')
   order by c.relname`);

const policies = q(`
  select tablename as table, policyname as name, cmd, permissive,
         array_to_string(roles, ', ') as roles, qual, with_check
    from pg_policies where schemaname = 'public'
   order by tablename, cmd, policyname`);

const grants = q(`
  select table_name as table, grantee, string_agg(distinct privilege_type, ', ' order by privilege_type) as privileges
    from information_schema.role_table_grants
   where table_schema = 'public' and grantee in ('anon','authenticated','service_role')
   group by table_name, grantee
   order by table_name, grantee`);

const functions = q(`
  select p.proname as name,
         pg_get_function_identity_arguments(p.oid) as args,
         case when p.prosecdef then 'DEFINER' else 'INVOKER' end as security,
         case p.provolatile when 'i' then 'immutable' when 's' then 'stable' else 'volatile' end as volatility,
         coalesce((select string_agg(g, ', ' order by g) from (
            select 'anon' as g where has_function_privilege('anon', p.oid, 'execute')
            union all select 'authenticated' where has_function_privilege('authenticated', p.oid, 'execute')
            union all select 'service_role' where has_function_privilege('service_role', p.oid, 'execute')
         ) x), '—') as callable_by,
         obj_description(p.oid, 'pg_proc') as note
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.prokind = 'f'
   order by p.proname, args`);

const views = q(`
  select c.relname as view,
         coalesce((select 'yes' from pg_options_to_table(c.reloptions) o
                    where o.option_name = 'security_invoker' and o.option_value = 'true'), 'NO') as security_invoker
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relkind = 'v'
   order by c.relname`);

const permissionKeys = q(`
  select key, module, label, security_relevant
    from public.permission_keys order by module, sort, key`);

/* ── Rendering ────────────────────────────────────────────────────────── */

const esc = (v) => (v === null || v === undefined ? "" : String(v).replace(/\|/g, "\\|").replace(/\n+/g, " ").trim());
const out = [];
const w = (line = "") => out.push(line);

const stamp = new Date().toISOString().slice(0, 10);
const migrationCount = q(`select count(*)::int as n from supabase_migrations.schema_migrations`)[0].n;

w(`# Authorization map — generated`);
w();
w(`**Generated ${stamp} from the live database, at ${migrationCount} applied migrations.**`);
w(`Do not edit this file: run \`node supabase/scripts/authorization-map.mjs\` from`);
w(`\`creditverse-platform\` and commit the result. Every line is read from`);
w(`\`pg_policies\`, \`pg_proc\`, \`pg_class\` and \`information_schema\` — nothing here is`);
w(`inferred from documentation, and nothing here states what SHOULD be true.`);
w();
w(`Doctrine is in \`CLAUDE.md\`. Behaviour is asserted per user against this same`);
w(`database by \`supabase/scripts/rls-matrix.mjs\`. This file is only the surface`);
w(`both of those talk about.`);
w();

/* The audit surface first: anything that can bypass a policy. */
const definers = functions.filter((f) => f.security === "DEFINER");
const definerReachable = definers.filter((f) => f.callable_by.includes("anon") || f.callable_by.includes("authenticated"));
w(`## The bypass surface — SECURITY DEFINER functions callable from the API`);
w();
w(`A DEFINER function runs as its owner, so row-level security does not narrow`);
w(`what it reads. These ${definerReachable.length} are reachable by a signed-in caller (or by \`anon\`),`);
w(`which makes each one a place where authorization has to be checked in the`);
w(`body. **A DEFINER function must never call an RLS-dependent INVOKER helper**`);
w(`— the helper would answer for the owner, not the caller.`);
w();
w(`| Function | Callable by | Volatility | What it is for |`);
w(`|---|---|---|---|`);
for (const f of definerReachable) {
  w(`| \`${esc(f.name)}(${esc(f.args)})\` | ${esc(f.callable_by)} | ${esc(f.volatility)} | ${esc(f.note) || "—"} |`);
}
w();
const anonFns = functions.filter((f) => f.callable_by.includes("anon"));
w(`**Callable by \`anon\` (an unauthenticated visitor): ${anonFns.length}.**`);
if (anonFns.length > 0) {
  w();
  for (const f of anonFns) w(`- \`${esc(f.name)}(${esc(f.args)})\` — ${esc(f.security)}`);
}
w();

w(`## Tables — row-level security and grants`);
w();
const noRls = tables.filter((t) => !t.rls);
w(`${tables.length} tables. **RLS enabled on ${tables.length - noRls.length}.**`);
if (noRls.length > 0) {
  w();
  w(`> Without RLS: ${noRls.map((t) => "`" + t.table + "`").join(", ")}`);
}
w();
const grantsFor = (t) => grants.filter((g) => g.table === t).map((g) => `${g.grantee}: ${g.privileges}`).join("; ") || "—";
const policiesFor = (t) => policies.filter((p) => p.table === t);
for (const t of tables) {
  const ps = policiesFor(t.table);
  w(`### \`${t.table}\`${t.rls ? "" : "  — ⚠️ NO ROW-LEVEL SECURITY"}`);
  w();
  if (t.note) w(`${esc(t.note)}`), w();
  w(`Grants — ${grantsFor(t.table)}`);
  w();
  if (ps.length === 0) {
    w(t.rls
      ? `**No policies.** With RLS on and no policy, nothing is readable or writable by \`anon\` or \`authenticated\` — default deny.`
      : `**No policies and no RLS.** Access is whatever the grants above allow.`);
  } else {
    w(`| Policy | Command | Roles | USING | WITH CHECK |`);
    w(`|---|---|---|---|---|`);
    for (const p of ps) {
      w(`| ${esc(p.name)}${p.permissive === "RESTRICTIVE" ? " *(restrictive)*" : ""} | ${esc(p.cmd)} | ${esc(p.roles)} | ${p.qual ? "`" + esc(p.qual) + "`" : "—"} | ${p.with_check ? "`" + esc(p.with_check) + "`" : "—"} |`);
    }
    const cmds = new Set(ps.map((p) => p.cmd));
    const missing = ["SELECT", "INSERT", "UPDATE", "DELETE"].filter((c) => !cmds.has(c) && !cmds.has("ALL"));
    if (missing.length > 0) w(), w(`No ${missing.join(" / ")} policy — that command is denied to \`anon\` and \`authenticated\`.`);
  }
  w();
}

w(`## Views`);
w();
w(`A view without \`security_invoker\` runs as its owner, so it does NOT apply the`);
w(`reader's policies to the tables underneath.`);
w();
w(`| View | security_invoker |`);
w(`|---|---|`);
for (const v of views) w(`| \`${esc(v.view)}\` | ${v.security_invoker === "yes" ? "yes" : "**NO**"} |`);
w();

w(`## Permission keys — the canonical named permissions`);
w();
w(`${permissionKeys.length} keys. \`security_relevant\` marks the ones whose default is deny.`);
w();
w(`| Key | Module | Label | Security-relevant |`);
w(`|---|---|---|---|`);
for (const k of permissionKeys) {
  w(`| \`${esc(k.key)}\` | ${esc(k.module)} | ${esc(k.label)} | ${k.security_relevant ? "yes" : "" } |`);
}
w();

w(`## Every function in \`public\``);
w();
w(`| Function | Security | Volatility | Callable by |`);
w(`|---|---|---|---|`);
for (const f of functions) {
  w(`| \`${esc(f.name)}(${esc(f.args)})\` | ${esc(f.security)} | ${esc(f.volatility)} | ${esc(f.callable_by)} |`);
}
w();

const text = out.join("\n") + "\n";
if (process.argv.includes("--stdout")) {
  process.stdout.write(text);
} else {
  writeFileSync("AUTHORIZATION_MAP.md", text);
  console.log(`AUTHORIZATION_MAP.md written — ${tables.length} tables, ${policies.length} policies, ${functions.length} functions, ${permissionKeys.length} permission keys`);
}
close();
