-- Every organization gets a permanent, human-readable Organization ID:
-- BES- + 6 characters from an alphabet without the look-alikes 0/O/1/I/L.
-- Generated by the database at creation, unique forever, immutable. It is a
-- display and support reference only — never an authorization key; membership
-- and RLS remain the gate.
create or replace function public.gen_org_public_id()
returns text language plpgsql volatile as $$
declare
  alphabet constant text := '23456789ABCDEFGHJKMNPQRSTUVWXYZ';
  v text := '';
  i int;
begin
  for i in 1..6 loop
    v := v || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
  end loop;
  return 'BES-' || v;
end $$;

alter table public.organizations add column public_id text;

-- Backfill: draw until unused (31^6 ≈ 887M ids; collisions are a retry, never a duplicate).
do $$
declare r record; v text;
begin
  for r in select id from public.organizations where public_id is null order by created_at loop
    loop
      v := public.gen_org_public_id();
      exit when not exists (select 1 from public.organizations where public_id = v);
    end loop;
    update public.organizations set public_id = v where id = r.id;
  end loop;
end $$;

alter table public.organizations alter column public_id set not null;
alter table public.organizations add constraint organizations_public_id_format
  check (public_id ~ '^BES-[23456789ABCDEFGHJKMNPQRSTUVWXYZ]{6}$');
create unique index organizations_public_id_key on public.organizations (public_id);

create or replace function public.organizations_assign_public_id()
returns trigger language plpgsql security definer set search_path = public as $$
declare v text;
begin
  if tg_op = 'UPDATE' then
    if new.public_id is distinct from old.public_id then
      raise exception 'Organization ID is permanent and cannot be changed' using errcode = '23514';
    end if;
    return new;
  end if;
  if new.public_id is null then
    loop
      v := public.gen_org_public_id();
      exit when not exists (select 1 from public.organizations where public_id = v);
    end loop;
    new.public_id := v;
  end if;
  return new;
end $$;
revoke execute on function public.organizations_assign_public_id() from public, anon, authenticated;
revoke execute on function public.gen_org_public_id() from public, anon, authenticated;
create trigger organizations_public_id before insert or update on public.organizations
  for each row execute function public.organizations_assign_public_id();
