-- The Organization ID is generated by the database; callers never supply it.
-- A column default lets INSERT omit it (and the generated API types make it
-- optional); the trigger still guarantees uniqueness by redrawing on the
-- astronomically rare collision. The generator must be executable by the
-- inserting role because column defaults run as the caller.
alter table public.organizations alter column public_id set default public.gen_org_public_id();
grant execute on function public.gen_org_public_id() to authenticated;

create or replace function public.organizations_assign_public_id()
returns trigger language plpgsql security definer set search_path = public as $$
declare v text;
begin
  if tg_op = 'UPDATE' then
    if new.public_id is distinct from old.public_id then
      raise exception 'Organization ID is permanent and cannot be changed' using errcode = '23514';
    end if;
    return new;
  end if;
  v := new.public_id;
  while v is null or exists (select 1 from public.organizations o where o.public_id = v) loop
    v := public.gen_org_public_id();
  end loop;
  new.public_id := v;
  return new;
end $$;
