-- Permanent, human-readable references (Dee, 2026-09-05): CN- for a client
-- (the person, in CreditOps and FundingOps alike) and FND- for a funding file
-- (one funding attempt). Same alphabet and rules as the Organization ID
-- (0043): no look-alike characters, generated by the database, unique
-- forever, immutable, and a display/support reference only — never an
-- authorization key. One person known to both products keeps one CN-: the
-- hand-off copies it onto the record it creates or links.
create or replace function public.gen_public_code(p_prefix text)
returns text language plpgsql volatile as $$
declare
  alphabet constant text := '23456789ABCDEFGHJKMNPQRSTUVWXYZ';
  v text := '';
  i int;
begin
  for i in 1..6 loop
    v := v || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
  end loop;
  return p_prefix || '-' || v;
end $$;

alter table public.fulfillment_clients add column if not exists public_id text;
alter table public.funding_clients      add column if not exists public_id text;
alter table public.funding_files        add column if not exists public_id text;

-- Backfill: linked pairs share one CN-; everything else draws until unused.
do $$
declare r record; v text;
begin
  for r in select id from public.fulfillment_clients where public_id is null order by created_at loop
    loop v := public.gen_public_code('CN'); exit when not exists (select 1 from public.fulfillment_clients where public_id = v) and not exists (select 1 from public.funding_clients where public_id = v); end loop;
    update public.fulfillment_clients set public_id = v where id = r.id;
  end loop;
  update public.funding_clients fc set public_id = c.public_id from public.fulfillment_clients c where fc.fulfillment_client_id = c.id and fc.public_id is null;
  for r in select id from public.funding_clients where public_id is null order by created_at loop
    loop v := public.gen_public_code('CN'); exit when not exists (select 1 from public.fulfillment_clients where public_id = v) and not exists (select 1 from public.funding_clients where public_id = v); end loop;
    update public.funding_clients set public_id = v where id = r.id;
  end loop;
  for r in select id from public.funding_files where public_id is null order by created_at loop
    loop v := public.gen_public_code('FND'); exit when not exists (select 1 from public.funding_files where public_id = v); end loop;
    update public.funding_files set public_id = v where id = r.id;
  end loop;
end $$;

alter table public.fulfillment_clients alter column public_id set not null;
alter table public.funding_clients      alter column public_id set not null;
alter table public.funding_files        alter column public_id set not null;
alter table public.fulfillment_clients alter column public_id set default public.gen_public_code('CN');
alter table public.funding_clients      alter column public_id set default public.gen_public_code('CN');
alter table public.funding_files        alter column public_id set default public.gen_public_code('FND');
alter table public.fulfillment_clients add constraint fulfillment_clients_public_id_format check (public_id ~ '^CN-[23456789ABCDEFGHJKMNPQRSTUVWXYZ]{6}$');
alter table public.funding_clients      add constraint funding_clients_public_id_format      check (public_id ~ '^CN-[23456789ABCDEFGHJKMNPQRSTUVWXYZ]{6}$');
alter table public.funding_files        add constraint funding_files_public_id_format        check (public_id ~ '^FND-[23456789ABCDEFGHJKMNPQRSTUVWXYZ]{6}$');
create unique index fulfillment_clients_public_id_key on public.fulfillment_clients (public_id);
create unique index funding_files_public_id_key on public.funding_files (public_id);
-- A funding client linked to a CreditOps client shares its CN-, so the funding-side index is per table only.
create unique index funding_clients_public_id_key on public.funding_clients (public_id);

/** Assign on insert; refuse any later change. */
create or replace function public.assign_client_public_id()
returns trigger language plpgsql security definer set search_path = public as $$
declare v text;
begin
  if tg_op = 'UPDATE' then
    if new.public_id <> old.public_id then raise exception 'public_id is immutable' using errcode = '22023'; end if;
    return new;
  end if;
  -- The column default draws a code; a collision (or a null) is repaired here. The hand-off's
  -- explicit copy of a linked CN- is a same-table uniqueness matter only.
  if new.public_id is not null and not exists (select 1 from public.fulfillment_clients where public_id = new.public_id and id <> new.id)
     and not exists (select 1 from public.funding_clients where public_id = new.public_id and id <> new.id) then return new; end if;
  if new.public_id is not null and tg_table_name = 'funding_clients' and exists (select 1 from public.fulfillment_clients where public_id = new.public_id) then return new; end if;
  loop
    v := public.gen_public_code('CN');
    exit when not exists (select 1 from public.fulfillment_clients where public_id = v) and not exists (select 1 from public.funding_clients where public_id = v);
  end loop;
  new.public_id := v;
  return new;
end $$;
create or replace function public.assign_funding_file_public_id()
returns trigger language plpgsql security definer set search_path = public as $$
declare v text;
begin
  if tg_op = 'UPDATE' then
    if new.public_id <> old.public_id then raise exception 'public_id is immutable' using errcode = '22023'; end if;
    return new;
  end if;
  if new.public_id is not null and not exists (select 1 from public.funding_files where public_id = new.public_id and id <> new.id) then return new; end if;
  loop v := public.gen_public_code('FND'); exit when not exists (select 1 from public.funding_files where public_id = v); end loop;
  new.public_id := v;
  return new;
end $$;
create trigger fulfillment_clients_public_id before insert or update of public_id on public.fulfillment_clients for each row execute function public.assign_client_public_id();
create trigger funding_clients_public_id     before insert or update of public_id on public.funding_clients     for each row execute function public.assign_client_public_id();
create trigger funding_files_public_id       before insert or update of public_id on public.funding_files       for each row execute function public.assign_funding_file_public_id();

-- Lenders: LDR- (Dee, same day). One catalogue entry, one permanent reference.
alter table public.lenders add column if not exists public_id text;
do $$
declare r record; v text;
begin
  for r in select id from public.lenders where public_id is null order by created_at loop
    loop v := public.gen_public_code('LDR'); exit when not exists (select 1 from public.lenders where public_id = v); end loop;
    update public.lenders set public_id = v where id = r.id;
  end loop;
end $$;
alter table public.lenders alter column public_id set not null;
alter table public.lenders alter column public_id set default public.gen_public_code('LDR');
alter table public.lenders add constraint lenders_public_id_format check (public_id ~ '^LDR-[23456789ABCDEFGHJKMNPQRSTUVWXYZ]{6}$');
create unique index lenders_public_id_key on public.lenders (public_id);
create or replace function public.assign_lender_public_id()
returns trigger language plpgsql security definer set search_path = public as $$
declare v text;
begin
  if tg_op = 'UPDATE' then
    if new.public_id <> old.public_id then raise exception 'public_id is immutable' using errcode = '22023'; end if;
    return new;
  end if;
  if new.public_id is not null and not exists (select 1 from public.lenders where public_id = new.public_id and id <> new.id) then return new; end if;
  loop v := public.gen_public_code('LDR'); exit when not exists (select 1 from public.lenders where public_id = v); end loop;
  new.public_id := v;
  return new;
end $$;
create trigger lenders_public_id before insert or update of public_id on public.lenders for each row execute function public.assign_lender_public_id();

-- The hand-off (0053) creates or links the other product's record: carry the CN- across so one person has one ID.
create or replace function public.handoff_copy_public_id()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  -- funding client just linked to a CreditOps client: adopt that client's CN- if this row still has a fresh one of its own
  if new.fulfillment_client_id is not null and (old.fulfillment_client_id is distinct from new.fulfillment_client_id) then
    update public.funding_clients set public_id = (select public_id from public.fulfillment_clients where id = new.fulfillment_client_id)
     where id = new.id and not exists (select 1 from public.funding_clients x where x.public_id = (select public_id from public.fulfillment_clients where id = new.fulfillment_client_id) and x.id <> new.id);
  end if;
  return new;
end $$;
create trigger funding_clients_handoff_public_id after update of fulfillment_client_id on public.funding_clients for each row execute function public.handoff_copy_public_id();
