/**
 * Seed data for the fulfillment client domain.
 * Demonstrates BOTH intake modes clearly so the division workspace can
 * render SaaS-pulled and outsourcing-only clients side by side.
 */

import type {
  FulfillmentClient,
  OutsourcingGroup,
} from "@/lib/fulfillment/fulfillment-client-domain";

/* ------------------------------------------------------------------ */
/* Outsourcing groups (Mode 2 partners — no BES SaaS)                  */
/* ------------------------------------------------------------------ */

export const seedOutsourcingGroups: OutsourcingGroup[] = [
  {
    id: "os-group-1",
    name: "CRC Outsourcing — Q3 Cohort",
    partnerName: "Credit Restoration Center",
    contactEmail: "ops@creditrestorationcenter.com",
    contractRef: "OS-2026-014",
    clientCount: 4,
    status: "Active",
    createdAt: "Jul 01, 2026",
  },
  {
    id: "os-group-2",
    name: "Metro Dispute Partners",
    partnerName: "Metro Dispute LLC",
    contactEmail: "fulfillment@metrodispute.com",
    contractRef: "OS-2026-021",
    clientCount: 2,
    status: "Onboarding",
    createdAt: "Aug 18, 2026",
  },
];

/* ------------------------------------------------------------------ */
/* Fulfillment clients — both modes                                    */
/* ------------------------------------------------------------------ */

export const seedFulfillmentClients: FulfillmentClient[] = [
  /* ===== MODE 1: SaaS-Pulled (clients running on BES CreditOps) ===== */
  {
    id: "fc-101",
    name: "Maria Gonzalez",
    email: "maria.g@gmail.com",
    phone: "(323) 555-0142",
    mode: "saas_pulled",
    organizationId: "sub-1",
    organizationName: "Apex Credit Co.",
    autoSync: true,
    status: "In Processing",
    round: "Round 2",
    assignedAgent: "Carlos Mendoza",
    openItems: 4,
    slaHoursRemaining: 4,
    lastActivity: "2 hours ago",
    createdAt: "May 02, 2026",
  },
  {
    id: "fc-102",
    name: "Anthony Ramos",
    email: "aramos@outlook.com",
    phone: "(310) 555-0198",
    mode: "saas_pulled",
    organizationId: "sub-1",
    organizationName: "Apex Credit Co.",
    autoSync: true,
    status: "Ready for QA",
    round: "Round 1",
    assignedAgent: "Keila Betancourt",
    openItems: 2,
    slaHoursRemaining: 12,
    lastActivity: "Today, 09:15 AM",
    createdAt: "Jun 14, 2026",
  },
  {
    id: "fc-103",
    name: "Tanya Brooks",
    email: "tanya.brooks@gmail.com",
    mode: "saas_pulled",
    organizationId: "sub-4",
    organizationName: "CreditFix Solutions",
    autoSync: true,
    status: "In Processing",
    round: "Round 1",
    assignedAgent: "Keila Betancourt",
    openItems: 12,
    slaHoursRemaining: 18,
    lastActivity: "1 hour ago",
    createdAt: "Aug 01, 2026",
  },
  {
    id: "fc-104",
    name: "Lisa Chen",
    email: "lisa.chen@gmail.com",
    mode: "saas_pulled",
    organizationId: "sub-4",
    organizationName: "CreditFix Solutions",
    autoSync: true,
    status: "Attention",
    round: "Round 2",
    assignedAgent: "Carlos Mendoza",
    openItems: 1,
    slaHoursRemaining: 2,
    lastActivity: "Yesterday",
    createdAt: "Jul 22, 2026",
  },
  {
    id: "fc-105",
    name: "James Whitaker",
    email: "jwhitaker@gmail.com",
    mode: "saas_pulled",
    organizationId: "sub-2",
    organizationName: "Pioneer Credit Solutions",
    autoSync: true,
    status: "Completed",
    round: "Completed",
    assignedAgent: "Carlos Mendoza",
    openItems: 0,
    lastActivity: "Aug 20, 2026",
    createdAt: "Mar 11, 2026",
  },

  /* ===== MODE 2: Outsourcing-Only (clients with their own system) ===== */
  {
    id: "fc-201",
    name: "Robert Kim",
    email: "rkim@yahoo.com",
    phone: "(713) 555-0231",
    mode: "outsourcing_only",
    outsourcingGroupId: "os-group-1",
    outsourcingGroupName: "CRC Outsourcing — Q3 Cohort",
    autoSync: false,
    status: "In Processing",
    round: "Round 1",
    assignedAgent: "Keila Betancourt",
    openItems: 8,
    slaHoursRemaining: 20,
    lastActivity: "3 hours ago",
    createdAt: "Aug 05, 2026",
  },
  {
    id: "fc-202",
    name: "Patricia Doyle",
    email: "patricia.doyle@gmail.com",
    mode: "outsourcing_only",
    outsourcingGroupId: "os-group-1",
    outsourcingGroupName: "CRC Outsourcing — Q3 Cohort",
    autoSync: false,
    status: "Awaiting Response",
    round: "Round 2",
    assignedAgent: "Carlos Mendoza",
    openItems: 3,
    slaHoursRemaining: 48,
    lastActivity: "Yesterday",
    createdAt: "Jul 18, 2026",
  },
  {
    id: "fc-203",
    name: "Marcus Bell",
    email: "m.bell@gmail.com",
    mode: "outsourcing_only",
    outsourcingGroupId: "os-group-1",
    outsourcingGroupName: "CRC Outsourcing — Q3 Cohort",
    autoSync: false,
    status: "Monitoring Issue",
    round: "Round 1",
    assignedAgent: "Keila Betancourt",
    openItems: 5,
    lastActivity: "2 days ago",
    createdAt: "Aug 10, 2026",
  },
  {
    id: "fc-204",
    name: "Diana Reyes",
    email: "diana.reyes@gmail.com",
    mode: "outsourcing_only",
    outsourcingGroupId: "os-group-2",
    outsourcingGroupName: "Metro Dispute Partners",
    autoSync: false,
    status: "Onboarding",
    round: "Pre-Round",
    assignedAgent: "Unassigned",
    openItems: 0,
    lastActivity: "Today",
    createdAt: "Aug 28, 2026",
  },
  {
    id: "fc-205",
    name: "Steven Park",
    email: "steven.park@gmail.com",
    mode: "outsourcing_only",
    outsourcingGroupId: "os-group-2",
    outsourcingGroupName: "Metro Dispute Partners",
    autoSync: false,
    status: "Onboarding",
    round: "Pre-Round",
    assignedAgent: "Unassigned",
    openItems: 0,
    lastActivity: "Today",
    createdAt: "Aug 29, 2026",
  },
];
