/**
 * Seed data for the FundingOps domain.
 *
 * Demonstrates BOTH intake modes (SaaS-synced + Agency Manual) and the
 * Client → Business → Funding File → Deal hierarchy. ~16 funding clients
 * across the partners with funding stages, lenders, amounts, assignees, SLAs.
 */

import type {
  FundingClient,
  FundingBusiness,
  FundingFile,
  FundingDeal,
} from "@/lib/fulfillment/fundingops-domain";
import type { OutsourcingGroup } from "@/lib/fulfillment/fulfillment-client-domain";

/* ------------------------------------------------------------------ */
/* Outsourcing groups (Mode 2 partners — no BES SaaS)                  */
/* ------------------------------------------------------------------ */

export const seedFundingGroups: OutsourcingGroup[] = [
  {
    id: "fos-group-1",
    name: "Meridian Capital Partners",
    partnerName: "Meridian Capital",
    contactEmail: "fulfillment@meridiancap.com",
    contractRef: "FOS-2026-007",
    clientCount: 3,
    status: "Active",
    createdAt: "Jul 12, 2026",
  },
  {
    id: "fos-group-2",
    name: "Summit Business Lending",
    partnerName: "Summit Business Lending",
    contactEmail: "ops@summitbl.com",
    contractRef: "FOS-2026-019",
    clientCount: 2,
    status: "Onboarding",
    createdAt: "Aug 20, 2026",
  },
];

/* ------------------------------------------------------------------ */
/* Funding clients — both modes                                        */
/* ------------------------------------------------------------------ */

export const seedFundingClients: FundingClient[] = [
  /* ===== Meridian Capital Partners (fos-group-1) — Agency Manual ===== */
  {
    id: "ffc-401",
    name: "James Whitaker",
    email: "jwhitaker@gmail.com",
    phone: "(212) 555-0310",
    mode: "outsourcing_only",
    provenance: "agency_manual",
    outsourcingGroupId: "fos-group-1",
    outsourcingGroupName: "Meridian Capital Partners",
    autoSync: false,
    status: "Document Review",
    assignedAgent: "Keila Betancourt",
    openFiles: 1,
    totalRequested: 250000,
    slaHoursRemaining: 12,
    lastActivity: "5 hours ago",
    createdAt: "Aug 10, 2026",
  },
  {
    id: "ffc-402",
    name: "Patricia Doyle",
    email: "patricia.doyle@gmail.com",
    mode: "outsourcing_only",
    provenance: "agency_manual",
    outsourcingGroupId: "fos-group-1",
    outsourcingGroupName: "Meridian Capital Partners",
    autoSync: false,
    status: "Submitted",
    assignedAgent: "Carlos Mendoza",
    openFiles: 1,
    totalRequested: 120000,
    slaHoursRemaining: 48,
    lastActivity: "Yesterday",
    createdAt: "Jul 18, 2026",
  },
  {
    id: "ffc-403",
    name: "Marcus Bell",
    email: "m.bell@gmail.com",
    mode: "outsourcing_only",
    provenance: "agency_manual",
    outsourcingGroupId: "fos-group-1",
    outsourcingGroupName: "Meridian Capital Partners",
    autoSync: false,
    status: "Onboarding",
    assignedAgent: "Unassigned",
    openFiles: 1,
    totalRequested: 75000,
    lastActivity: "2 days ago",
    createdAt: "Aug 25, 2026",
  },

  /* ===== Summit Business Lending (fos-group-2) — Agency Manual ===== */
  {
    id: "ffc-501",
    name: "Diana Reyes",
    email: "diana.reyes@gmail.com",
    phone: "(619) 555-0442",
    mode: "outsourcing_only",
    provenance: "agency_manual",
    outsourcingGroupId: "fos-group-2",
    outsourcingGroupName: "Summit Business Lending",
    autoSync: false,
    status: "Onboarding",
    assignedAgent: "Unassigned",
    openFiles: 1,
    totalRequested: 200000,
    lastActivity: "Today",
    createdAt: "Aug 28, 2026",
  },
  {
    id: "ffc-502",
    name: "Steven Park",
    email: "steven.park@gmail.com",
    mode: "outsourcing_only",
    provenance: "agency_manual",
    outsourcingGroupId: "fos-group-2",
    outsourcingGroupName: "Summit Business Lending",
    autoSync: false,
    status: "Readiness Review",
    assignedAgent: "Keila Betancourt",
    openFiles: 1,
    totalRequested: 95000,
    slaHoursRemaining: 30,
    lastActivity: "Today",
    createdAt: "Aug 29, 2026",
  },

  /* ===== EDP Management Group (fsub-4) — Native FundingOps SaaS ===== */
  {
    id: "ffc-601",
    name: "Sofia Castellano",
    email: "sofia.castellano@gmail.com",
    phone: "(305) 555-0567",
    mode: "saas_pulled",
    provenance: "bes_saas_synced",
    organizationId: "fsub-4",
    organizationName: "EDP Management Group",
    autoSync: true,
    status: "Offer Received",
    assignedAgent: "Carlos Mendoza",
    openFiles: 1,
    totalRequested: 400000,
    slaHoursRemaining: 20,
    lastActivity: "1 hour ago",
    createdAt: "Jul 30, 2026",
  },
  {
    id: "ffc-602",
    name: "Anthony Ramos",
    email: "aramos@outlook.com",
    mode: "saas_pulled",
    provenance: "bes_saas_synced",
    organizationId: "fsub-4",
    organizationName: "EDP Management Group",
    autoSync: true,
    status: "Lender Matching",
    assignedAgent: "Keila Betancourt",
    openFiles: 2,
    totalRequested: 220000,
    slaHoursRemaining: 16,
    lastActivity: "4 hours ago",
    createdAt: "Aug 12, 2026",
  },
  {
    id: "ffc-603",
    name: "Lisa Chen",
    email: "lisa.chen@gmail.com",
    mode: "saas_pulled",
    provenance: "bes_saas_synced",
    organizationId: "fsub-4",
    organizationName: "EDP Management Group",
    autoSync: true,
    status: "Funded",
    assignedAgent: "Carlos Mendoza",
    openFiles: 0,
    totalRequested: 0,
    lastActivity: "Aug 08, 2026",
    createdAt: "Jan 22, 2026",
  },
];

/* ------------------------------------------------------------------ */
/* Businesses — a client may own multiple businesses                    */
/* ------------------------------------------------------------------ */

export const seedFundingBusinesses: FundingBusiness[] = [
  {
    id: "fb-401",
    clientId: "ffc-401",
    legalName: "Whitaker Plumbing Inc.",
    industry: "Trade Services",
    annualRevenue: "$890K",
    timeInBusiness: "5 years",
  },
  {
    id: "fb-402",
    clientId: "ffc-402",
    legalName: "Doyle Boutique LLC",
    industry: "Retail",
    annualRevenue: "$340K",
    timeInBusiness: "3 years",
  },
  {
    id: "fb-403",
    clientId: "ffc-403",
    legalName: "Bell Cleaning Services",
    industry: "Janitorial",
    annualRevenue: "$180K",
    timeInBusiness: "1 year",
  },
  {
    id: "fb-501",
    clientId: "ffc-501",
    legalName: "Reyes Landscaping LLC",
    industry: "Landscaping",
    annualRevenue: "$420K",
    timeInBusiness: "4 years",
  },
  {
    id: "fb-502",
    clientId: "ffc-502",
    legalName: "Park Tech Solutions",
    industry: "IT Services",
    annualRevenue: "$510K",
    timeInBusiness: "3 years",
  },
  {
    id: "fb-601",
    clientId: "ffc-601",
    legalName: "Castellano Med Spa LLC",
    industry: "Healthcare",
    annualRevenue: "$1.5M",
    timeInBusiness: "6 years",
  },
  {
    id: "fb-602",
    clientId: "ffc-602",
    legalName: "Ramos Logistics LLC",
    industry: "Transportation",
    annualRevenue: "$780K",
    timeInBusiness: "4 years",
  },
  {
    id: "fb-603",
    clientId: "ffc-603",
    legalName: "Chen Bakery Inc.",
    industry: "Food Service",
    annualRevenue: "$290K",
    timeInBusiness: "2 years",
  },
];

/* ------------------------------------------------------------------ */
/* Funding files — one funding cycle per business request              */
/* ------------------------------------------------------------------ */

export const seedFundingFiles: FundingFile[] = [
  {
    id: "ff-401",
    clientId: "ffc-401",
    businessId: "fb-401",
    businessName: "Whitaker Plumbing Inc.",
    purpose: "Restaurant Expansion",
    requestedAmount: 250000,
    stage: "Document Review",
    assignedAgent: "Keila Betancourt",
    dealCount: 0,
    slaHoursRemaining: 12,
    lastActivity: "5 hours ago",
    createdAt: "Aug 10, 2026",
  },
  {
    id: "ff-402",
    clientId: "ffc-402",
    businessId: "fb-402",
    businessName: "Doyle Boutique LLC",
    purpose: "Equipment Financing",
    requestedAmount: 120000,
    stage: "Submitted",
    assignedAgent: "Carlos Mendoza",
    dealCount: 1,
    slaHoursRemaining: 48,
    lastActivity: "Yesterday",
    createdAt: "Jul 18, 2026",
  },
  {
    id: "ff-403",
    clientId: "ffc-403",
    businessId: "fb-403",
    businessName: "Bell Cleaning Services",
    purpose: "Working Capital",
    requestedAmount: 75000,
    stage: "Readiness Review",
    assignedAgent: "Unassigned",
    dealCount: 0,
    lastActivity: "2 days ago",
    createdAt: "Aug 25, 2026",
  },
  {
    id: "ff-501",
    clientId: "ffc-501",
    businessId: "fb-501",
    businessName: "Reyes Landscaping LLC",
    purpose: "Working Capital",
    requestedAmount: 200000,
    stage: "Readiness Review",
    assignedAgent: "Unassigned",
    dealCount: 0,
    lastActivity: "Today",
    createdAt: "Aug 28, 2026",
  },
  {
    id: "ff-502",
    clientId: "ffc-502",
    businessId: "fb-502",
    businessName: "Park Tech Solutions",
    purpose: "Equipment Financing",
    requestedAmount: 95000,
    stage: "Readiness Review",
    assignedAgent: "Keila Betancourt",
    dealCount: 0,
    slaHoursRemaining: 30,
    lastActivity: "Today",
    createdAt: "Aug 29, 2026",
  },
  {
    id: "ff-601",
    clientId: "ffc-601",
    businessId: "fb-601",
    businessName: "Castellano Med Spa LLC",
    purpose: "Working Capital",
    requestedAmount: 400000,
    stage: "Offer Received",
    assignedAgent: "Carlos Mendoza",
    dealCount: 1,
    slaHoursRemaining: 20,
    lastActivity: "1 hour ago",
    createdAt: "Jul 30, 2026",
  },
  {
    id: "ff-602a",
    clientId: "ffc-602",
    businessId: "fb-602",
    businessName: "Ramos Logistics LLC",
    purpose: "Equipment Financing",
    requestedAmount: 120000,
    stage: "Lender Matching",
    assignedAgent: "Keila Betancourt",
    dealCount: 0,
    slaHoursRemaining: 16,
    lastActivity: "4 hours ago",
    createdAt: "Aug 12, 2026",
  },
  {
    id: "ff-602b",
    clientId: "ffc-602",
    businessId: "fb-602",
    businessName: "Ramos Logistics LLC",
    purpose: "Working Capital",
    requestedAmount: 100000,
    stage: "Lender Matching",
    assignedAgent: "Keila Betancourt",
    dealCount: 0,
    slaHoursRemaining: 16,
    lastActivity: "4 hours ago",
    createdAt: "Aug 12, 2026",
  },
  {
    id: "ff-603",
    clientId: "ffc-603",
    businessId: "fb-603",
    businessName: "Chen Bakery Inc.",
    purpose: "Working Capital",
    requestedAmount: 75000,
    stage: "Funded",
    assignedAgent: "Carlos Mendoza",
    dealCount: 1,
    lastActivity: "Aug 08, 2026",
    createdAt: "Jan 22, 2026",
  },
];

/* ------------------------------------------------------------------ */
/* Deals — lender submissions inside funding files                      */
/* ------------------------------------------------------------------ */

export const seedFundingDeals: FundingDeal[] = [
  {
    id: "fd-402",
    fileId: "ff-402",
    clientId: "ffc-402",
    lender: "Funding Circle",
    program: "Equipment Loan",
    amount: 120000,
    rate: "14%",
    term: "36mo",
    status: "Submitted",
    stipsOutstanding: 1,
    submittedAt: "1 day ago",
  },
  {
    id: "fd-402b",
    fileId: "ff-402",
    clientId: "ffc-402",
    lender: "OnDeck",
    program: "Working Capital",
    amount: 100000,
    rate: "18%",
    term: "12mo",
    status: "In Review",
    stipsOutstanding: 0,
    submittedAt: "3 days ago",
  },
  {
    id: "fd-601",
    fileId: "ff-601",
    clientId: "ffc-601",
    lender: "Triton Capital",
    program: "Working Capital",
    amount: 400000,
    rate: "12%",
    term: "24mo",
    status: "Offer Received",
    stipsOutstanding: 0,
    submittedAt: "4 days ago",
  },
  {
    id: "fd-601b",
    fileId: "ff-601",
    clientId: "ffc-601",
    lender: "Credibly",
    program: "Business LOC",
    amount: 250000,
    rate: "15%",
    term: "18mo",
    status: "Stipulations",
    stipsOutstanding: 2,
    submittedAt: "2 days ago",
  },
  {
    id: "fd-602a",
    fileId: "ff-602a",
    clientId: "ffc-602",
    lender: "Square Capital",
    program: "Working Capital",
    amount: 120000,
    rate: "16%",
    term: "12mo",
    status: "Submitted",
    stipsOutstanding: 1,
    submittedAt: "Today",
  },
  {
    id: "fd-602b",
    fileId: "ff-602b",
    clientId: "ffc-602",
    lender: "BlueVine",
    program: "Equipment Financing",
    amount: 100000,
    rate: "13%",
    term: "24mo",
    status: "Draft",
    stipsOutstanding: 0,
    submittedAt: "Today",
  },
  {
    id: "fd-603",
    fileId: "ff-603",
    clientId: "ffc-603",
    lender: "OnDeck",
    program: "Working Capital",
    amount: 75000,
    rate: "19%",
    term: "12mo",
    status: "Funded",
    stipsOutstanding: 0,
    submittedAt: "Jul 15, 2026",
    fundedDate: "Aug 08, 2026",
  },
  {
    id: "fd-603b",
    fileId: "ff-603",
    clientId: "ffc-603",
    lender: "Triton Capital",
    program: "Renewal — Working Capital",
    amount: 110000,
    rate: "14%",
    term: "12mo",
    status: "Submitted",
    stipsOutstanding: 0,
    submittedAt: "Yesterday",
  },
];
